const FALLBACK_DB={active:'rocoso',projects:{rocoso:{id:'rocoso',name:'Rocoso – Apertura Heladería',icon:'🍦',owner:'Carlos Pérez',deadline:'15 nov 2026',weeks:6,dates:['S1','S2','S3','S4','S5','S6'],budget:[100000,200000,50000,150000,250000,100000],actualBudget:[95000,210000,48000,null,null,null],items:[{id:'a1',icon:'📄',name:'Contrato del local',plan:1,actual:1},{id:'a2',icon:'🛠️',name:'Diseño arquitectónico',plan:1,actual:2},{id:'a3',icon:'📋',name:'Cotizaciones de obra',plan:1,actual:1},{id:'a4',icon:'👥',name:'Contratista',plan:2,actual:2},{id:'a5',icon:'🏪',name:'Compra de equipos',plan:2,actual:2},{id:'a6',icon:'🍴',name:'Definir menú inicial',plan:2,actual:2},{id:'a7',icon:'🔨',name:'Demolición',plan:3,actual:3},{id:'a8',icon:'🔌',name:'Instalaciones',plan:3,actual:null,reprogram:4},{id:'a9',icon:'📁',name:'Permisos y licencias',plan:3,actual:3},{id:'a10',icon:'❄️',name:'Refrigeración',plan:4,actual:null},{id:'a11',icon:'🪑',name:'Mobiliario y decoración',plan:4,actual:null},{id:'a12',icon:'👨‍🍳',name:'Capacitación del equipo',plan:5,actual:null},{id:'a13',icon:'📣',name:'Marketing y lanzamiento',plan:5,actual:null},{id:'a14',icon:'🎉',name:'Apertura oficial',plan:6,actual:null}]}}};
const API_URL=window.PLAN_SEMANAL_API_URL||'';
const LS_KEY='planSemanalDB_v1';
function localDB(){return JSON.parse(localStorage.getItem(LS_KEY))||structuredClone(FALLBACK_DB)}
function saveLocal(db){localStorage.setItem(LS_KEY,JSON.stringify(db));return db}
async function api(action,payload={}){if(!API_URL){let db=localDB();return localAction(db,action,payload)}try{return await jsonp(API_URL,{action,payload:JSON.stringify(payload)})}catch(e){console.warn('API falló, usando localStorage:',e);let db=localDB();return localAction(db,action,payload)}}
function jsonp(url,params){return new Promise((resolve,reject)=>{const cb='ps_cb_'+Date.now()+'_'+Math.random().toString(16).slice(2);const qs=new URLSearchParams({...params,callback:cb});const script=document.createElement('script');const timer=setTimeout(()=>{cleanup();reject(new Error('Timeout API'))},15000);function cleanup(){clearTimeout(timer);delete window[cb];script.remove()}window[cb]=(res)=>{cleanup();res&&res.ok?resolve(res.data):reject(new Error(res?.error||'Error API'))};script.src=url+(url.includes('?')?'&':'?')+qs.toString();script.onerror=()=>{cleanup();reject(new Error('No se pudo cargar Apps Script'))};document.body.appendChild(script)})}
function localAction(db,action,payload){switch(action){case'getDB':return db;case'saveDB':return saveLocal(payload.db);case'createProject':{let id='p'+Date.now();db.projects[id]={id,name:'Nuevo proyecto',icon:'🗺️',owner:'',deadline:'',weeks:6,dates:['S1','S2','S3','S4','S5','S6'],budget:[0,0,0,0,0,0],actualBudget:[null,null,null,null,null,null],items:[]};db.active=id;return saveLocal(db)}case'saveProject':{db.projects[payload.project.id]=payload.project;db.active=payload.project.id;return saveLocal(db)}case'deleteItem':{let p=db.projects[payload.projectId];p.items=p.items.filter(x=>x.id!==payload.itemId);return saveLocal(db)}case'saveWeekly':{let p=db.projects[payload.projectId];p.items=payload.items;p.actualBudget=payload.actualBudget;return saveLocal(db)}default:return db}}
function money(n){return n==null?'—':'$'+Number(n).toLocaleString('es-MX')}
function activeProject(db){return db.projects[db.active]||Object.values(db.projects)[0]}
function nav(active){document.querySelectorAll('.nav a').forEach(a=>a.classList.toggle('active',a.dataset.nav===active))}
function projectOptions(db,projectId){return Object.values(db.projects).map(p=>`<option value="${p.id}" ${p.id===projectId?'selected':''}>${p.name}</option>`).join('')}
function setProject(id,page){let db=localDB();db.active=id;saveLocal(db);location.href=page||location.pathname}
function renderHeader(db,project,page){document.getElementById('projectIcon').textContent=project.icon||'🗺️';document.getElementById('projectTitle').textContent=project.name;document.getElementById('projectMeta').innerHTML=`<span>📅 Fecha compromiso: ${project.deadline||'—'}</span><span>👤 Responsable: ${project.owner||'—'}</span><span>💵 Presupuesto total: ${money((project.budget||[]).reduce((a,b)=>a+(Number(b)||0),0))}</span>`;document.getElementById('topActions').innerHTML=`<select onchange="setProject(this.value,'${page}')">${projectOptions(db,project.id)}</select>`}
